flashcard_app/urls.py
from django.conf.urls import patterns, url
from flashcard_app import views

urlpatterns = patterns('',
        url(r'^view_groups/$', views.view_flashcard_groups, name = 'view_flashcard_groups'),
        url(r'^create/(?P<groupname>\w+)/$', views.create_flashcard, name = 'create_flashcard'),
        url(r'^view/(?P<groupname>\w+)/$', views.view_flashcards, name = 'view_flashcards'),
        url(r'^practice/(?P<groupname>\w+)/(?P<side>\w+)/generate_flashcard/$', views.generate_flashcard, name = 'generate_flashcard'),         
        url(r'^practice/(?P<groupname>\w+)/(?P<side>\w+)/$', views.practice_flashcards, name = 'practice_flashcards'),
        url(r'^practice/(?P<groupname>\w+)/(?P<side>\w+)/results/$', views.results, name = 'results'),
        
)

flashcards/urls.py
from django.conf.urls import patterns, include, url
from flashcard_app import views

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'flashcards.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/$', views.user_login, name = 'login'),
    url(r'^logout/$', views.user_logout, name = 'logout'),
    url(r'^register_redirect/$', views.register_redirect, name = 'register_redirect'),
    url(r'^register/$', views.register, name = 'register'),
    url(r'^delete_group/$', views.delete_flashcard_group, name = "delete_flashcard_group"),
    url(r'^delete_flashcard/$', views.delete_flashcard, name = "delete_flashcard"),
    url(r'^(?P<username>\w+)/home/$', views.home, name = 'home'),                   
    url(r'^(?P<username>\w+)/flashcards/', include('flashcard_app.urls')),
    url(r'^(?P<username>\w+)/create_flashcard_group/$', views.create_flashcard_group, name = 'create_flashcard_group'),
    
    url(r'^check_flashcard/$', views.check_flashcard, name = "check_flashcard"),
    url(r'^$', views.index, name='index'),
)

flashcard_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class FlashcardGroup(models.Model):
    name = models.CharField(max_length=50)
    user = models.ForeignKey(User)
    front_side = models.CharField(max_length=50)
    back_side = models.CharField(max_length=50)
    
    def __unicode__(self):
        return self.name
    
    
class Flashcard(models.Model):
    frontside = models.CharField(max_length=50)
    backside = models.CharField(max_length=50)
    active = models.BooleanField(default = True)
    times_wrong = models.IntegerField(default = 0)
    times_to_repeat = models.IntegerField(default = 0)
    group = models.ForeignKey(FlashcardGroup)
    
    def __unicode__(self):
        return self.frontside + " / " + self.backside
    

flashcard_app/forms.py
from django import forms
from flashcard_app.models import Flashcard, FlashcardGroup
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    #Hides the password as the user types it
    password = forms.CharField(widget=forms.PasswordInput())
    
    class Meta:
        model = User
        fields = ('username', 'email', 'password')
        
        
class FlashcardGroupForm(forms.ModelForm):
    
    front_side = forms.CharField(label = "Front Side", max_length=50)
    back_side = forms.CharField(label = "Back Side", max_length=50)
    
    class Meta:
        model = FlashcardGroup
        fields = ('name', 'front_side', 'back_side')
        
class FlashcardForm(forms.ModelForm):
    
    class Meta:
        model = Flashcard
        fields = ('frontside', 'backside')
        
        

flashcard_app/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render_to_response
from django.template import RequestContext
from flashcard_app.forms import UserForm, FlashcardForm, FlashcardGroupForm
from flashcard_app.models import Flashcard, FlashcardGroup
from random import randint

import json


# Create your views here.
def index(request):
    context = RequestContext(request)
    
    #Redirects the user to his home page if logged in
    if request.user.is_authenticated():
        print (request.user)
        return HttpResponseRedirect('/' + request.user.username + '/home/')
        
    #If not logged in, user will see the index page
    return render_to_response('flashcard_app/index.html', {}, context)


def home(request, username):
    context = RequestContext(request)
    
    current_user = request.user
    
    #Grabs all of the user's flashcard sets to display them
    flashcard_group_list = FlashcardGroup.objects.filter(user=current_user)
    
    return render_to_response('flashcard_app/home.html', {'flashcard_group_list': flashcard_group_list}, context)

def register_redirect(request):
    
    context = RequestContext(request)
    
    #This page is set to redirect the user to login after they register
    return render_to_response('flashcard_app/register_redirect.html', {}, context)

def register(request):
    context = RequestContext(request)
    registered = False
    
    user_form = UserForm(data=request.POST)
    if request.method == 'POST': #If the user has submitted the form, the request must be POST
        if user_form.is_valid(): #Checks to make sure the form has been completed properly

                new_user = user_form.save(commit = False) #Waits to save until password is hashed

                #Hashes the user's password to protect it
                new_user.set_password(new_user.password)
                new_user.save() #Saves to the database

                registered = True
                
                return HttpResponseRedirect('/register_redirect/')
        else:
            print (user_form.errors) #If the form was filled out improperly, the errors will be printed
    else:
        #If the request was not POST, then the user is looking for a blank form
        user_form = UserForm()
    
    return render_to_response(
            'flashcard_app/register.html',
            {'user_form': user_form, 'registered': registered},
            context)

def user_login(request):
    context = RequestContext(request)
    
    if request.method == 'POST':
        
        username = request.POST['username']
        password = request.POST['password']
        
        user = authenticate(username = username, password = password)
        
        if user:
            login(request, user)
            return HttpResponseRedirect('/')
        else:
            message = "Invalid username and/or password"
            return render_to_response('flashcard_app/login.html', {'message': message}, context)
    else:
        return render_to_response('flashcard_app/login.html', {}, context)
    
def user_logout(request):
    logout(request)
    
    return HttpResponseRedirect('/')
    
@login_required
def create_flashcard_group(request, username):
    context = RequestContext(request)
    
    created = False
    
    #If we're POSTing, that means the form has been submitted and
    #we can grab data from it
    if request.method == 'POST': 
        flashcard_group_form = FlashcardGroupForm(data=request.POST)
        
        if flashcard_group_form.is_valid():
            flashcard_group = flashcard_group_form.save(commit = False)
            
            current_user = request.user
            flashcard_group.user = current_user
            flashcard_group.save()
            
            created = True
            
            return HttpResponseRedirect("/" + request.user.username + "/home/")
        else:
            print (flashcard_group_form.errors)
    #If request is a GET, just render a blank form
    else: 
        flashcard_group_form = FlashcardGroupForm()
        
    return render_to_response('flashcard_app/create_flashcard_group.html', {'flashcard_group_form': flashcard_group_form}, context)
    
@login_required
def create_flashcard(request, username, groupname):
    context = RequestContext(request)
    
    failed = False

    if request.method == 'POST':
        flashcard_form = FlashcardForm(data=request.POST)
        
        if flashcard_form.is_valid():
            flashcard = flashcard_form.save(commit = False)
            
            current_user = request.user #Grabs the current user from Django

            flashcard.group = FlashcardGroup.objects.get(name=groupname, user = current_user)
            
            try:
                duplicate = Flashcard.objects.get(group = flashcard.group, frontside = flashcard.frontside, backside = flashcard.backside)
                failed = True
            except Flashcard.DoesNotExist:
                flashcard.save()

        else:
            print (flashcard_form.errors)
    else:
        current_user = request.user #Grabs the current user from Django
        flashcard_form = FlashcardForm()
        
    group = FlashcardGroup.objects.get(name=groupname, user = current_user)
    print (group.front_side, group.back_side)
    return render_to_response('flashcard_app/create_flashcard.html', {'flashcard_form': flashcard_form, 'groupname': groupname, 'failed': failed, 'group' : group}, context)

@login_required   
def view_flashcard_groups(request, username):
    context = RequestContext(request)
    
    current_user = request.user
    
    flashcard_group_list = FlashcardGroup.objects.filter(user=current_user) #Grabs the list of cards matching the current user
    
    return render_to_response('flashcard_app/view_flashcard_groups.html', {'flashcard_group_list':flashcard_group_list}, context)

@login_required
def view_flashcards(request, username, groupname):
    context = RequestContext(request)
    
    current_user = request.user
    
    current_group = FlashcardGroup.objects.get(name = groupname)
    
    flashcard_list = Flashcard.objects.filter(group = current_group) #Grabs the list of cards matching the current user and group
    
    return render_to_response('flashcard_app/view_flashcards.html', {'flashcard_list':flashcard_list, 'group': current_group}, context)

@login_required
def practice_flashcards(request, username, groupname, side):
    context = RequestContext(request)
    current_user = request.user
    
    current_group = FlashcardGroup.objects.get(name = groupname)
    
    flashcard_list = Flashcard.objects.filter(group = current_group)
    
    for item in flashcard_list:
        item.times_wrong = 0
        item.active = True
        item.save()
    
    #Grabs the list of cards matching the current user
    flashcard_list_length = Flashcard.objects.filter(group = current_group).count()
    
    if flashcard_list_length > 0:
        rand_card_index = randint(0,flashcard_list_length-1) #Picks a random number in the range of possible indexes
        my_card = flashcard_list[rand_card_index] #Saves the card in a variable
    
        return render_to_response('flashcard_app/practice_flashcards.html', {'my_card':my_card, 'groupname':groupname, 'side': side}, context)
    
    else:
        return HttpResponse("No cards in this group")
@login_required    
def check_flashcard(request):
    context = RequestContext(request)
    
    if request.is_ajax():
        if request.method == "POST":
            
            answer = request.POST['answer']
            question = request.POST['question']
            true_back = request.POST['true_back']
            side = request.POST['side']
            
            group = FlashcardGroup.objects.get(name=request.POST['groupname'])
            
            
            if side == 'front':
                try:
                    Flashcard.objects.get(frontside = question, backside = answer, group = group)
                    return HttpResponse("Correct")
                except:
                    try:
                        f = Flashcard.objects.get(frontside = question, backside = true_back, group = group)
                    except (Exception, err):
                        print (Exception, err)

                    print ("got here")
                    f.times_to_repeat += 2
                    f.times_wrong += 1
                    f.save()
            elif side == 'back':
                try:
                    #If the user is doing a drill where flashcard back's are the prompts and fronts
                    #are the answers, then the variables in the 'get' must be reversed
                    Flashcard.objects.get(frontside = answer, backside = question, group = group)
                    return HttpResponse("Correct")
                except:
                    try:
                        f = Flashcard.objects.get(frontside = true_back, backside = question, group = group)
                    except (Exception, err):
                        print (Exception, err)

                    print ("got here")
                    f.times_to_repeat += 2
                    f.times_wrong += 1
                    f.save()
            
        return HttpResponse('Wrong')
    
@login_required
def generate_flashcard(request, username, groupname, side):
    context = RequestContext(request)
    current_user = request.user
    
    current_group = FlashcardGroup.objects.get(name = groupname, user = current_user)

    flashcard_list = Flashcard.objects.filter(group = current_group)
    
    if side == 'front':
    
        try:
            used_card = Flashcard.objects.get(frontside = request.POST['question'], group = current_group)
        except (Exception, err):

templates/flashcard_app/check_card.html
{{ correct }}

templates/flashcard_app/create_flashcard.html
{% extends 'flashcard_app/base.html' %}
{% block title %}Create Flashcard{% endblock %}

{% load bootstrap3 %}
{% load static %}

{% block head_block %}

<link href = "{% static 'css/create_flashcard.css' %}" rel = "stylesheet">
<script src = "{% static 'js/create_flashcard.js' %}"></script>

{% endblock %}

{% block body_block %}

    <h1>Create flashcards</h1>

    <p id = "front_side" style = "display:none">{{group.front_side}}</p>
    <p id = "back_side" style = "display:none">{{group.back_side}}</p>


    <div class = "row">
        <div class = "col-xs-6">

            {% if failed %}
                <p class = "error">Flashcard already exists!</p>
            {% else %}
                <p>&nbsp;</p>
            {% endif %}

            <form id = "flashcard_form" method = "post" action = "/{{user.username}}/flashcards/create/{{groupname}}/"
                enctype = "multipart/form-data">


                {% csrf_token %}

                <div class="form-group">
                    <label class="control-label" for="id_frontside">{{group.front_side}}</label>
                        <input class="form-control" id="id_frontside" maxlength="50" name="frontside" placeholder="Frontside" required="required" title="" type="text" />
                </div>

                <div class="form-group">
                    <label class="control-label" for="id_backside">{{group.back_side}}</label>
                        <input class="form-control" id="id_backside" maxlength="50" name="backside" placeholder="Backside" required="required" title="" type="text" />
                </div>

                <div class="form-group">

                    <button type="submit" class="m-btn" style="margin-top:-10px">
                        Add Card
                    </button>

                </div>
        </div>
        <div class = "col-xs-6" id = "sidebar">

            <div class = "row">
                <a href = "/{{user}}/flashcards/view/{{groupname}}/ "class = "m-btn">View Set</a>
            </div>
            <div class = "row">
                <a href = "/{{user}}/home" class = "m-btn">Home</a>
            </div>
        </div>
    </div>
{% endblock %}

templates/flashcard_app/create_flashcard_group.html
{% extends 'flashcard_app/base.html' %}
{% load static %}

{% load bootstrap3 %}

{% bootstrap_css %}
{% bootstrap_javascript %}

{% block title %}Create group{% endblock %}
{% block head_block %}

<link href = "{% static 'css/create_flashcard_group.css' %}" rel = "stylesheet">
<script src = "{% static 'js/create_flashcard_group.js' %}"></script>

{% endblock %}
{% block body_block %}

<div class = "group_form">

    <div class = "row">
        
        <br /><br /><br /><br /><br /><br /><br />
    
        <form id = "user_form" method = "post" action = ""
        enctype = "multipart/form-data">

        {% csrf_token %}
        
        {% bootstrap_form flashcard_group_form %}
    
        
        {% buttons %}
                    <button type="submit" class="m-btn">
                        Submit
                    </button>
        {% endbuttons %}
    </div>
</form>
    
    </div>

</div>


{% endblock %}

templates/flashcard_app/flashcard.html
{% if side == 'front' %}

<div id = "question">{{my_card.frontside}}</div>

<p id = "true_back" style = "display:none">{{my_card.backside}}</p>

{% elif side == 'back' %}

<div id = "question">{{my_card.backside}}</div>

<p id = "true_back" style = "display:none">{{my_card.frontside}}</p>

{% endif %}

templates/flashcard_app/home.html
{% extends 'flashcard_app/base.html' %}
{% load static %}
{% block title_block %}Home{% endblock %}
{% block head_block %}

<link href = "{% static 'css/home.css' %}" rel = "stylesheet">
<script src = "{% static 'js/home.js' %}" rel = "stylehseet"></script>

{% endblock %}
{% block body_block %}

    <h1>Hello {{user.username}}</h1>

    <div class = "row">
        <div id = "list" class = "col-xs-6">
            <h2>My Flashcard Sets</h2>
            <div class = "antiscroll-wrap">
                <ul id = "groups" class="nav antiscroll-inner">
                    {% for item in flashcard_group_list %}
                        <li><div class = "m-btn-group"><a class = "m-btn groupname" href = "/{{user.username}}/flashcards/view/{{item.name}}">{{item.name}}</a><i class="m-btn red icn-only delete"><i class="icon-remove icon-white"></i></i></div></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <div id = "sidebar" class = "col-xs-6 center-block">
            <a class = "m-btn"href = "/{{user.username}}/create_flashcard_group/">New Set</a>
        </div>
    </div>
{% endblock %}

templates/flashcard_app/index.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>LRN</title>
        <script src="{% static 'js/jquery.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/m-dropdown.min.js' %}"></script>
        <script src="{% static 'js/m-radio.min.js' %}"></script>
        <link href="{% static 'css/bootstrap.min.css' %}"rel="stylesheet">
        <link href = "{% static 'css/m-styles.min.css' %}"rel="stylesheet">
        <link href = "{% static 'css/index.css' %}" rel = "stylesheet">
    </head>

    <body>
        <header class="top" role="header">
            <div id = "navigation" class="container">
                <a href="/" class="navbar-brand pull-left">
                    LRN
                </a>
                <nav class="navbar-collapse collapse" role="navigation">
                    <ul class="navbar-nav nav pull-right">
                        <li><a href="/register/">Register</a></li>
                        {% if user.is_authenticated %}
                        <li><a href = "/logout/">Logout</a></li>
                        {% else %}
                        <li><a href="/login/">Login</a></li>
                        {% endif %}
                    </ul>
                </nav>
            </div> 
            
        </header>
    
    <div class="banner">
        <div class="container">
            <h1>LRN: A simple study aid</h1>
            <p>A quick, easy to use flashcard system to help you master any subject</p>
        </div>
    </div>

    <div class="middle">
        <div class="container">
            <div class="col-md-9 content">
                <h2>Use LRN's study tools to study more efficiently anywhere, anytime</h2>
                <p>Memorization can be a pain.  With LRN, it doesn't have to be.  With our flashcard drill system you'll have the power to conquer any subject, whether it be history or biology.  Signing up is free and always will be.</p>
                <div class="to-tutorial">
                    <p><strong>Sign up now to get started:</strong></p>
                    <a href="/register/" class="m-btn green">Sign Up</a>
                </div>
            </div>
            <div id = "sidebar" class="col-md-3 pull-right">
            </div>
        </div>
    </div>
        
    <div class="bottom">
        <div class="container">
        </div>
    </div>
        
    </body>

templates/flashcard_app/login.html
{% extends 'flashcard_app/base.html' %}
{% block title %}Login{% endblock %}
{% load static %}
{% block head_block%}<link href="{% static 'css/login.css' %}"rel="stylesheet">{% endblock %}

{% block body_block %}

            <h1>Login</h1>

            {% if message %}
            <p class = "error">{{message}}</p>
            {% else %}
            <p>&nbsp;</p>
            {% endif %}

            <form id = "login_form" method = "post" action = "/login/">

                {% csrf_token %}

                <input type = "text" name = "username" value = "" size = "50" class = "form-control" placeholder="username" autofocus/>
                <input type = "password" name = "password" value = "" size = "50" class = "form-control" placeholder = "password"/>
                <input type = "submit" value = "Login" class = "m-btn"/>

            </form>
{% endblock %}

templates/flashcard_app/practice_finished.html
Drill finished!

templates/flashcard_app/practice_flashcards.html
{% extends 'flashcard_app/base.html' %}
{% load static %}
{% block title %}Test{% endblock %}
{% block head_block %}

    <script src="{% static 'js/practice.js' %}"></script>
    <link href = "{% static 'css/practice_flashcards.css' %}" rel = "stylesheet"/>

{% endblock %}
{% block body_block %}

    <h1 id = "groupname">{{groupname}}</h1>
        
    <div id = "flashcard">

        {% if side == 'front' %}
        
        <div id = "question">{{my_card.frontside}}</div>
        <p id = "true_back" style = "display:none">{{my_card.backside}}</p>
        <p id = "side" style = "display:none">{{side}}</p>
        
        {% elif side == 'back' %}
        
        <div id = "question">{{my_card.backside}}</div>
        <p id = "true_back" style = "display:none">{{my_card.frontside}}</p>
        <p id = "side" style = "display:none">{{side}}</p>
        
        {% endif %}

    </div>

    <br />

    <form id="category_form" method = "POST" autocomplete="off">

        {% csrf_token %}

        <input class = "form-control" id = "answer" type = "text" name = "text" autocomplete="off" autofocus/>
        


        <input class = "m-btn" id = "submit" type = "button" name = "submit" value = "Submit"/>
        <input class = "m-btn" id = "continue" type = "button" name = "continue" value = "Continue"/>
        
    </form>
{% endblock %}

templates/flashcard_app/register.html
{% extends 'flashcard_app/base.html' %}


{% load static %}
{% load bootstrap3 %}

{% bootstrap_css %}
{% bootstrap_javascript %}

{% block title %}Register{% endblock %}
{% block head_block%}

<link href="{% static 'css/register.css' %}"rel="stylesheet">
<script src = "{% static 'js/register.js' %}"></script>

{% endblock %}
{% block body_block %}

            <h1>Register</h1>

            <form id = "user_form" method = "post" action = "/register/"
                enctype = "multipart/form-data">

                {% csrf_token %}

                {% bootstrap_form user_form %}
                {% buttons %}
                    <button type="submit" class="m-btn" style="margin-top:-10px">
                        Submit
                    </button>
                {% endbuttons %}


            </form>

{% endblock %}

templates/flashcard_app/register_redirect.html
{% extends 'flashcard_app/base.html' %}


{% load static %}
{% load bootstrap3 %}

{% bootstrap_css %}
{% bootstrap_javascript %}

{% block title %}Login Successful!{% endblock %}

{% block head_block%}

<meta http-equiv="refresh" content="3;url=/login/" />
<link href="{% static 'css/register.css' %}"rel="stylesheet">

{% endblock %}

{% block body_block %}
    
    <h1 style = "text-align:center">Registration successful!</h1>
    <p style = "text-align:center">You will now be redirected to the login page...</p>


{% endblock %}

templates/flashcard_app/results.html
{% extends 'flashcard_app/base.html' %}

{% load static %}

{% block head_block %}

<link href = "{% static 'css/results.css' %}" rel="stylesheet">
<script src = "{% static 'js/results.js' %}"></script>

{% endblock %}

{% block body_block %}

<h1>Results</h1>

<div class = "col-md-6">
    
    
    <h2>Score: {{score}}%</h2>
    
    
    <h3>Cards to review:</h3>
    <div class = "antiscroll-wrap">
        <table class = "table table-bordered table-striped antiscroll-inner">

            <thead>

                <tr>

                    <th>Flashcard</th>
                    <th>Times wrong</th>

                </tr>

            </thead>

            <tbody>

                    {% for item in answered_incorrectly %}

                    <tr>
                        <td>{{item}}</td>
                        <td>{{item.times_wrong}}</td>
                    </tr>

                    {% endfor %}

            </tbody>
            </div>
        </table>
    </div>

</div>

<div id = "sidebar" class = "col-md-6">

    <a class = "m-btn" href = "/{{user.username}}/flashcards/practice/{{groupname}}/">Retry</a>
    <a class = "m-btn" href = "/">Home</a>

</div>

{% endblock %}

templates/flashcard_app/view_flashcard_groups.html
{% extends 'flashcard_app/base.html' %}
{% block title %}{{user.username}}'s flashcards{% endblock %}
{% block head_block %}

<script>
    $(document).ready(function () {
        
        $('.antiscroll-wrap').antiscroll();
        
    });
</script>

{% endblock %}

{% block body_block %}
    <div class = "antiscroll-wrap">
        <div class = "antiscroll-inner">
            <ul>
            {% for flashcard_group in flashcard_group_list %}
                <li><a href = "/{{user.username}}/flashcards/view/{{flashcard_group}}">{{flashcard_group}}</a>
                    <a href = "/{{user.username}}/flashcards/create/{{flashcard_group}}/">Create Card</a>
                    <a href = "/{{user.username}}/flashcards/practice/{{flashcard_group}}/">Practice</a></li>
            {% endfor %}
            </ul>
        </div>
    </div>
    
{% endblock %}

templates/flashcard_app/view_flashcards.html
{% extends 'flashcard_app/base.html' %}
{% block title %}{{groupname}}{% endblock %}
{% load static %}
{% block head_block %}

<link href = "{% static 'css/view_flashcards.css' %}" rel = "stylesheet"/>
<script src = "{% static 'js/view_flashcards.js' %}"></script>

{% endblock %}
{% block body_block %}

    

    <div class = "view_cards">
        
            <h1>{{groupname}}</h1>
            
            <div class = "row">
                <div class = "col-xs-6">
                    <h2>Flashcards</h2>
                    <div class = "antiscroll-wrap">
                        <ul id = "flashcards" class="nav antiscroll-inner">
                            {% for item in flashcard_list %}
                            <li><div class = "m-btn-group"><a class = "m-btn flashcardname">{{item}}</a><a href="#" class="m-btn red icn-only delete"><i class="icon-remove icon-white"></i></a></div></li> <!--Added <a> tag for bootstrap styling-->
                            {% endfor %}
                    </ul>
                    </div>
                </div>
                <div id = "sidebar" class = "col-xs-6 center-block">

                    {% if flashcard_list|length > 0 %}
                    <a class = "m-btn" id = "practice" href = "/{{user.username}}/flashcards/practice/{{group}}/front/">Practice {{group.front_side}} to {{group.back_side}}</a>
                    <a class = "m-btn" id = "practice" href = "/{{user.username}}/flashcards/practice/{{group}}/back/">Practice {{group.back_side}} to {{group.front_side}}</a>
                    {% endif %}
                    <a class = "m-btn" href = "/{{user.username}}/flashcards/create/{{group}}/">Add Cards</a>
                </div>
            </div>
        </div>
    </div>
    
{% endblock %}